# Reattempting to create the Excel file for the 30-day social media plan for MJ IT Marketing Agency
import pandas as pd

# Data for the 30-day plan
mj_it_plan = [
    {"Day": "Day 1", "Post Type": "Image Post", "Topic": "Introduction to MJ IT Marketing",
     "Creative Idea": "Showcase your company logo, tagline, and key services in a sleek design.",
     "Suggestions": "Add a friendly team photo or founder's video to connect personally."},
    {"Day": "Day 2", "Post Type": "Carousel Post", "Topic": "Services Overview",
     "Creative Idea": "Highlight core services like SEO, Social Media Marketing, PPC, and Web Development.",
     "Suggestions": "Create slides explaining each service briefly with benefits."},
    {"Day": "Day 3", "Post Type": "Reel", "Topic": "A Day in the Life",
     "Creative Idea": "Behind-the-scenes look at your team working on a project.",
     "Suggestions": "Add a voiceover or captions explaining your workflow."},
    {"Day": "Day 4", "Post Type": "Image Post", "Topic": "Why Digital Marketing?",
     "Creative Idea": "Share statistics about the importance of digital marketing for businesses.",
     "Suggestions": "Use visually appealing infographics to display the data."},
    {"Day": "Day 5", "Post Type": "Story Post", "Topic": "Meet the Team",
     "Creative Idea": "Feature a short intro for one of your team members.",
     "Suggestions": "Add fun facts about them to make it engaging."},
    {"Day": "Day 6", "Post Type": "Video Post", "Topic": "Client Testimonial",
     "Creative Idea": "Share a success story from a happy client in a short video.",
     "Suggestions": "Include before-and-after metrics if possible."},
    {"Day": "Day 7", "Post Type": "Poll/Interactive Post", "Topic": "Marketing Goals",
     "Creative Idea": "Ask your audience what their main marketing goals are (e.g., brand awareness, leads).",
     "Suggestions": "Use the poll results to create a follow-up post with tailored advice."},
    {"Day": "Day 8", "Post Type": "Image Post", "Topic": "Free Marketing Tip",
     "Creative Idea": "Share a quick, actionable tip for social media growth.",
     "Suggestions": "Use bold visuals and hashtags to increase shareability."},
    {"Day": "Day 9", "Post Type": "Infographic", "Topic": "Anatomy of a Successful Campaign",
     "Creative Idea": "Break down the elements of a great digital marketing campaign.",
     "Suggestions": "Highlight case studies from your own projects."},
    {"Day": "Day 10", "Post Type": "Story Post", "Topic": "Client Feature",
     "Creative Idea": "Spotlight a client’s business you’ve worked with and their journey.",
     "Suggestions": "Tag the client to increase reach and build goodwill."},
    {"Day": "Day 11", "Post Type": "Image Post", "Topic": "SEO Basics",
     "Creative Idea": "Educate your audience on SEO essentials and their impact.",
     "Suggestions": "Include a CTA for a free consultation or SEO audit."},
    {"Day": "Day 12", "Post Type": "Reel", "Topic": "Website Makeover",
     "Creative Idea": "Show a before-and-after transformation of a website your team has revamped.",
     "Suggestions": "Add a step-by-step narrative for clarity."},
    {"Day": "Day 13", "Post Type": "Image Post", "Topic": "Common Marketing Mistakes",
     "Creative Idea": "Highlight common mistakes businesses make in digital marketing and how to avoid them.",
     "Suggestions": "Use humor or memes for relatability."},
    {"Day": "Day 14", "Post Type": "Story Post", "Topic": "Ask MJ IT Anything",
     "Creative Idea": "Open a Q&A for followers to ask marketing-related questions.",
     "Suggestions": "Answer creatively with visuals or short videos."},
    {"Day": "Day 15", "Post Type": "Image Post", "Topic": "Social Media Trends",
     "Creative Idea": "Share the latest trends in social media marketing.",
     "Suggestions": "Use real examples to back up your insights."},
    {"Day": "Day 16", "Post Type": "Reel", "Topic": "Client Journey",
     "Creative Idea": "Create a video showcasing the client onboarding process at MJ IT Marketing.",
     "Suggestions": "Include customer testimonials and team interactions."},
    {"Day": "Day 17", "Post Type": "Carousel Post", "Topic": "Case Study Highlight",
     "Creative Idea": "Showcase a detailed case study from one of your successful campaigns.",
     "Suggestions": "Use a visually appealing layout to make it easy to swipe through."},
    {"Day": "Day 18", "Post Type": "Infographic", "Topic": "Marketing Funnel Explained",
     "Creative Idea": "Educate your audience on the stages of a marketing funnel and its importance.",
     "Suggestions": "Include a link to your blog or free resources for deeper learning."},
    {"Day": "Day 19", "Post Type": "Reel", "Topic": "Fun Friday!",
     "Creative Idea": "Share a lighthearted moment from the team or a fun marketing-related skit.",
     "Suggestions": "Use trending audio for better reach."},
    {"Day": "Day 20", "Post Type": "Image Post", "Topic": "Special Offers",
     "Creative Idea": "Announce discounts or free consultations for new clients.",
     "Suggestions": "Use urgency-based copy like 'Limited Time Offer.'"},
    {"Day": "Day 21", "Post Type": "Story Post", "Topic": "Productivity Hacks",
     "Creative Idea": "Share tips on how your team stays productive.",
     "Suggestions": "Include tools or apps your team uses for work efficiency."},
    {"Day": "Day 22", "Post Type": "Reel", "Topic": "Ad Creation Process",
     "Creative Idea": "Show snippets of how your team brainstorms, designs, and implements an ad campaign.",
     "Suggestions": "Use quick transitions and upbeat music to keep it engaging."},
    {"Day": "Day 23", "Post Type": "Image Post", "Topic": "Debunk Marketing Myths",
     "Creative Idea": "Address common misconceptions about digital marketing.",
     "Suggestions": "Use a carousel format to explain each myth and the truth."},
    {"Day": "Day 24", "Post Type": "Story Post", "Topic": "Client Reviews",
     "Creative Idea": "Repost positive reviews and comments from clients.",
     "Suggestions": "Add stickers or GIFs to make it more lively."},
    {"Day": "Day 25", "Post Type": "Image Post", "Topic": "Importance of PPC",
     "Creative Idea": "Educate your audience on why Pay-Per-Click advertising works.",
     "Suggestions": "Include a CTA for a free PPC audit."},
    {"Day": "Day 26", "Post Type": "Poll/Interactive Post", "Topic": "Favorite Social Media Platform",
     "Creative Idea": "Ask your audience about their go-to platform (e.g., Instagram, Facebook, LinkedIn).",
     "Suggestions": "Share insights on how to best utilize each platform based on the poll results."},
    {"Day": "Day 27", "Post Type": "Video Post", "Topic": "Marketing Trends to Watch",
     "Creative Idea": "Share predictions for the next quarter/year in digital marketing.",
     "Suggestions": "Add visuals of current trends in action."},
    {"Day": "Day 28", "Post Type": "Image Post", "Topic": "How We Help",
     "Creative Idea": "Showcase the tangible results you provide (e.g., increased traffic, higher engagement).",
     "Suggestions": "Use bold metrics like '50% growth in 3 months!'"},
    {"Day": "Day 29", "Post Type": "Story Post", "Topic": "Behind the Brand",
     "Creative Idea": "Share your company’s mission, vision, and values.",
     "Suggestions": "Use a montage of team activities or milestones."},
    {"Day": "Day 30", "Post Type": "Thank You Post", "Topic": "Gratitude and Growth",
     "Creative Idea": "A heartfelt post thanking customers for their trust and support.",
     "Suggestions": "Include a celebratory video or milestones you’ve achieved."}
]

# Convert to DataFrame
mj_it_plan_df = pd.DataFrame(mj_it_plan)

# Save to Excel
mj_it_output_file = "MJ_IT_30Day_Plan.xlsx"
mj_it_plan_df.to_excel(mj_it_output_file, index=False, sheet_name="30-Day Plan")


